exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        files: ^.*\.(js|jsx|ts|md|tsx|rst|yml)$
        args: ["--ignore-words", ".codespellignore" ]      


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: "Prettier - Format Code"
        files: \.(ts|tsx|js|json|md|yaml|html|css)$
        args: ["--config", ".prettierrc"]
        additional_dependencies:
        -   prettier@2.1.2
        -   prettier-plugin-tailwindcss

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: ''  
    hooks:
    -   id: eslint
        name: "ESLint - Lint TypeScript files"
        files: \.(ts|tsx)$
        args: ["--fix", "--max-warnings=0"]    
        additional_dependencies:
        -   eslint
        -   eslint-plugin-tailwindcss
        -   "@next/eslint-plugin-next
        -   eslint-config-next
        -   eslint-config-prettier
