services:
  app:
    container_name: folio
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      # target: dev
    # volumes:
    #   # - .:/opt/node_app/app
    #   # - ./package.json:/opt/node_app/package.json
    #   # - ./package-lock.json:/opt/node_app/package-lock.json
    #   # - ./node_modules:/app/node_modules # Mount node_modules to preserve it after install
    #   # - notused:/opt/node_app/app/node_modules
    ports:
      # - ${PORT}:${PORT}
      - 3000:3000
      - 9229:9229
      - 9230:9230
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./
    #       target: /app
    #     - action: rebuild
    #       path: package.json
    #     - action: rebuild
    #       path: package-lock.json
    # command: > # node --allow-worker /node_modules/.bin/next build
    #   sleep infinity

volumes:
  notused:
