services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=ubuntu:latest
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
    command: /bin/sh -c "while sleep 1000; do :; done"
